# A serverless service that sends out emails via Mailgun

service:
  name: email_service
  description: 'A service that sends out emails.'

custom:
  defaultStage: prod
  currentStage: ${opt:stage, self:custom.defaultStage}
  currentRegion: ${file(./config.${self:custom.currentStage}.json):region}

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${self:custom.currentStage}
  region: ${self:custom.currentRegion}
  environment:
    EVENT_GATEWAY_URL: ${file(./config.${self:custom.currentStage}.json):EVENT_GATEWAY_URL}
    EVENT_GATEWAY_CONFIG_URL: ${file(./config.${self:custom.currentStage}.json):EVENT_GATEWAY_CONFIG_URL}
    MAILGUN_APIKEY: ${file(./config.${self:custom.currentStage}.json):MAILGUN_APIKEY}
    MAILGUN_DOMAIN: ${file(./config.${self:custom.currentStage}.json):MAILGUN_DOMAIN}

functions:
  sendWelcomeEmail:
    handler: handler.sendWelcomeEmail
    events:
      - user.created
