# users-api crud service

service:
  name: users-service
  description: 'Users CRUD service.'

custom:
  defaultStage: prod
  currentStage: ${opt:stage, self:custom.defaultStage}
  currentRegion: ${file(./config.${self:custom.currentStage}.json):region}

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${self:custom.currentStage}
  region: ${self:custom.currentRegion}
  environment:
    EVENT_GATEWAY_URL: ${file(./config.${self:custom.currentStage}.json):EVENT_GATEWAY_URL}
    EVENT_GATEWAY_CONFIG_URL: ${file(./config.${self:custom.currentStage}.json):EVENT_GATEWAY_CONFIG_URL}

functions:
  registerUser:
    handler: handler.registerUser
    events:
      - http:
          path: /users
          method: POST
          # cors has to be commented out until we change how data is sent to the Event Gateway
          # cors: true

  getUser:
    handler: handler.getUser
    events:
      - http:
          # Path params aren't isn't supported yet
          # path: /users/{id}
          path: /users/123
          method: GET
          # cors: true
          # request:
          #   parameters:
          #     paths:
          #       id: true
