# A template for a new serverless service

service:
  name: template_service # replace 'template'
  description: 'A template service for starting a new service.'

custom:
  defaultStage: prod
  currentStage: ${opt:stage, self:custom.defaultStage}
  currentRegion: ${file(./config.${self:custom.currentStage}.json):region}

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${self:custom.currentStage}
  region: ${self:custom.currentRegion}
  environment:
    EVENT_GATEWAY_URL: ${file(./config.${self:custom.currentStage}.json):EVENT_GATEWAY_URL}
    EVENT_GATEWAY_CONFIG_URL: ${file(./config.${self:custom.currentStage}.json):EVENT_GATEWAY_CONFIG_URL}

functions:
